import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Header from "./components/StaticBars/Header";
import Footer from "./components/StaticBars/Footer";
import { NextAuthProvider } from "./Providers";
import { getServerSession } from "next-auth";
import { StoreProvider } from "./redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <body className={inter.className}>
          <ChakraProvider>
            <StoreProvider>
              <Header />
              {children}
              <Footer />
            </StoreProvider>
          </ChakraProvider>
        </body>
      </NextAuthProvider>
    </html>
  );
}
